import { RouteInfo } from './sidebar.metadata';
import { Role } from 'src/app/shared/security/role';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: '-- Main',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Byer Modules
  {
    path: '',
    title: 'Home',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BUYER'],
    submenu: [
      {
        path: '/buyer/dashboard/main',
        title: 'Dashboard',
        moduleName: 'dashboard',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/buyer/dashboard/dashboard2',
        title: 'Price Forecaast',
        moduleName: 'dashboard',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'My Orders',
    moduleName: 'order',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BUYER'],
    submenu: [
      {
        path: '/buyer/orders/order',
        title: 'Pending',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/buyer/orders/accepted_order',
        title: 'Accepted',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/buyer/orders/shipped_order',
        title: 'Shipped',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/buyer/orders/delivered_order',
        title: 'Delivered',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '/buyer/products/product',
    title: 'Products',
    moduleName: 'products',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BUYER'],
    submenu: [],
  },
  {
    path: '/buyer/settings',
    title: 'Settings',
    moduleName: 'buyer',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BUYER'],
    submenu: [],
  },
  {
    path: '/apps/chat',
    title: 'Chat',
    moduleName: 'apps',
    iconType: 'material-icons-two-tone',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['BUYER'],
    submenu: [],
  },
  
  // Seller Modules
  {
    path: '/seller/dashboard',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SELLER'],
    submenu: [],
  },
  {
    path: '',
    title: 'My Orders',
    moduleName: 'order',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SELLER'],
    submenu: [
      {
        path: '/seller/orders/order',
        title: 'Pending',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/seller/orders/accepted_order',
        title: 'Accepted',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/seller/orders/shipped_order',
        title: 'Shipped',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/seller/orders/delivered_order',
        title: 'Delivered',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Products',
    moduleName: 'products',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SELLER'],
    submenu: [
      {
        path: '/seller/products/my-products',
        title: 'My Products',
        moduleName: 'products',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/seller/products/add-product',
        title: 'Add Product',
        moduleName: 'products',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '/seller/settings',
    title: 'Settings',
    moduleName: 'settings',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SELLER'],
    submenu: [],
  },
  {
    path: '/apps/chat',
    title: 'Chat',
    moduleName: 'apps',
    iconType: 'material-icons-two-tone',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['SELLER'],
    submenu: [],
  },
  // Driver Modules
  {
    path: '/driver/dashboard',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['DRIVER'],
    submenu: [],
  },
  {
    path: '',
    title: 'My Orders',
    moduleName: 'order',
    iconType: 'material-icons-two-tone',
    icon: 'face',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['DRIVER'],
    submenu: [
      {
        path: '/driver/orders/order',
        title: 'All Orders',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/driver/orders/accepted_order',
        title: 'Accepted',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/driver/orders/shipped_order',
        title: 'Shipped',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/driver/orders/delivered_order',
        title: 'Delivered',
        moduleName: 'order',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '/apps/chat',
    title: 'Chat',
    moduleName: 'apps',
    iconType: 'material-icons-two-tone',
    icon: 'chat',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['DRIVER'],
    submenu: [],
  },
  {
    path: '/driver/settings',
    title: 'Settings',
    moduleName: 'settings',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['DRIVER'],
    submenu: [],
  },
  {
    path: '/authentication/signin',
    title: 'Logout',
    moduleName: 'logout',
    iconType: 'material-icons-two-tone',
    icon: 'power_settings_new',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
];
